# Generated by Django 5.0.2 on 2024-02-12 21:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='education',
            old_name='id',
            new_name='education_id',
        ),
    ]
